### ISSUE TITLE
Broken links for lucid.distribute and lucid.package

### ISSUE THREAD

**Issue by zane** [razum2um/awesome-clojure#101]
The links for lucid.distribute (http://docs.caudate.me/lucidity/lucid-distribute.html) and lucid.package (http://docs.caudate.me/lucidity/lucid-package.html) are broken. [caudate.me](http://caudate.me/) appears to no longer exist.

**Comment by razum2um** [comment]
fixed in f7f0d06a12032d7a68579d08b7d162f241f9f356
